In [2]:
from sklearn.linear_model import LogisticRegression
import pandas  as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [60]:
data=pd.read_csv('bank-full.csv',sep=';')
data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [67]:
import statsmodels.formula.api as smf
data['no']=(data['y']=='no').astype(int)
data=data.drop('y',axis=1)
data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,no
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,1
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,1
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,1
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,1
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,1

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  no         45211 non-null  int32
dtypes: int32(1), int64(7), object(9)
memory usage: 5.7+ MB

In [69]:
m=smf.ols('no~{}',data=data).fit()
m.summary()

ValueError: negative dimensions are not allowed

In [70]:
df=pd.get_dummies(data,drop_first=True)
df.head()

,age,balance,day,duration,campaign,pdays,previous,no,job_blue-collar,job_entrepreneur,...,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_other,poutcome_success,poutcome_unknown
0,58,2143,5,261,1,-1,0,1,False,False,...,False,False,False,True,False,False,False,False,False,True
1,44,29,5,151,1,-1,0,1,False,False,...,False,False,False,True,False,False,False,False,False,True
2,33,2,5,76,1,-1,0,1,False,True,...,False,False,False,True,False,False,False,False,False,True
3,47,1506,5,92,1,-1,0,1,True,False,...,False,False,False,True,False,False,False,False,False,True
4,33,1,5,198,1,-1,0,1,False,False,...,False,False,False,True,False,False,False,False,False,True

In [43]:
lr=LogisticRegression()

In [76]:
y=df['no']
x=np.column_stack((np.ones(len(df)),df.drop('no',axis=1)))

In [77]:
lr.fit(x,y)

C:\Users\PC 10\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [80]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y,lr.predict(x))

array([[ 1124,  4165],
       [  751, 39171]], dtype=int64)

In [87]:
164*(165/10)-165**2/20+np.log(0.4)

1343.8337092681259

In [88]:
164*(160/10)-160**2/20+np.log(0.6)

1343.489174376234