# Workflow
1. Import Data
2. Check data
3. Decide which model
4. Results-model

In [1]:
# for classification task
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
bank = pd.read_csv("bank-full.csv",delimiter=';')

In [9]:
bank.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [18]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [24]:
bank.shape

(45211, 17)

In [40]:
bank['y']=bank['y'].map({'yes':1,'no':0})

In [32]:
import statsmodels.formula.api as smf

In [42]:
string_cols = ' + '.join(bank.columns[:-1])
results = smf.logit('y ~ {}'.format(string_cols), data=bank).fit()
results.summary()

Optimization terminated successfully.
         Current function value: 0.238463
         Iterations 8

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                45211
Model:                          Logit   Df Residuals:                    45168
Method:                           MLE   Df Model:                           42
Date:                Mon, 06 Apr 2026   Pseudo R-squ.:                  0.3392
Time:                        09:33:02   Log-Likelihood:                -10781.
converged:                       True   LL-Null:                       -16315.
Covariance Type:            nonrobust   LLR p-value:                     0.000
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 -2.5356      0.184    -13.803      0.000      -2.896      -2.176
job[T.blue-collar]        -0.3099      0.073     -4.264      0.000      -0.452      -0.167
job[T.entrepreneur]       -0.3571      0.126     -2.844      0.004      -0.603      -0.111
job[T.housemaid]          -0.5040      0.136     -3.693      0.000      -0.771      -0.237
job[T.management]         -0.1653      0.073     -2.255      0.024      -0.309      -0.022
job[T.retired]             0.2524      0.097      2.596      0.009       0.062       0.443
job[T.self-employed]      -0.2983      0.112     -2.664      0.008      -0.518      -0.079
job[T.services]           -0.2238      0.084     -2.662      0.008      -0.389      -0.059
job[T.student]             0.3821      0.109      3.505      0.000       0.168       0.596
job[T.technician]         -0.1760      0.069     -2.553      0.011      -0.311      -0.041
job[T.unemployed]         -0.1767      0.112     -1.583      0.113      -0.396       0.042
job[T.unknown]            -0.3133      0.233     -1.342      0.180      -0.771       0.144
marital[T.married]        -0.1795      0.059     -3.046      0.002      -0.295      -0.064
marital[T.single]          0.0925      0.067      1.375      0.169      -0.039       0.224
education[T.secondary]     0.1835      0.065      2.833      0.005       0.057       0.311
education[T.tertiary]      0.3789      0.075      5.031      0.000       0.231       0.527
education[T.unknown]       0.2505      0.104      2.411      0.016       0.047       0.454
default[T.yes]            -0.0167      0.163     -0.102      0.918      -0.336       0.302
housing[T.yes]            -0.6754      0.044    -15.395      0.000      -0.761      -0.589
loan[T.yes]               -0.4254      0.060     -7.091      0.000      -0.543      -0.308
contact[T.telephone]      -0.1634      0.075     -2.173      0.030      -0.311      -0.016
contact[T.unknown]        -1.6232      0.073    -22.183      0.000      -1.767      -1.480
month[T.aug]              -0.6939      0.078     -8.842      0.000      -0.848      -0.540
month[T.dec]               0.6911      0.177      3.912      0.000       0.345       1.037
month[T.feb]              -0.1473      0.089     -1.648      0.099      -0.323       0.028
month[T.jan]              -1.2617      0.122    -10.367      0.000      -1.500      -1.023
month[T.jul]              -0.8308      0.077    -10.733      0.000      -0.983      -0.679
month[T.jun]               0.4536      0.094      4.843      0.000       0.270       0.637
month[T.mar]               1.5899      0.120     13.265      0.000       1.355       1.825
month[T.may]              -0.3991      0.072     -5.521      0.000      -0.541      -0.257
month[T.nov]              -0.8734      0.084    -10.347      0.000      -1.039      -0.708
month[T.oct]               0.8814      0.108      8.159      0.000       0.670       1.093
month[T.sep]               0.8741      0.119      7.314      0.000       0.640       1.108
poutcome[T.other]          0.2035      0.090      2.265      0.024       0.027       0.380
poutcome[T.success]        2.2911      0.082     27.821      0.000       2.130       2.452
poutcome[T.unknown]       -0.0918      0.093     -0.982      0.326      -0.275       0.091
age                        0.0001      0.002      0.051      0.959      -0.004       0.004
balance                 1.284e-05   5.15e-06      2.493      0.013    2.75e-06    2.29e-05
day                        0.0100      0.002      3.993      0.000       0.005       0.015
duration                   0.0042   6.45e-05     64.985      0.000       0.004       0.004
campaign                  -0.0908      0.010     -8.955      0.000      -0.111      -0.071
pdays                     -0.0001      0.000     -0.335      0.737      -0.001       0.000
previous                   0.0102      0.007      1.561      0.118      -0.003       0.023
==========================================================================================
"""

In [50]:
# using sk learn

df_dummy=pd.get_dummies(bank,drop_first=True) #remove the first variable that being created. Total variables is n.
df_dummy.head()
# encounter categorical variables, manual convert the variables

,age,balance,day,duration,campaign,pdays,previous,y,job_blue-collar,job_entrepreneur,...,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_other,poutcome_success,poutcome_unknown
0,58,2143,5,261,1,-1,0,0,False,False,...,False,False,False,True,False,False,False,False,False,True
1,44,29,5,151,1,-1,0,0,False,False,...,False,False,False,True,False,False,False,False,False,True
2,33,2,5,76,1,-1,0,0,False,True,...,False,False,False,True,False,False,False,False,False,True
3,47,1506,5,92,1,-1,0,0,True,False,...,False,False,False,True,False,False,False,False,False,True
4,33,1,5,198,1,-1,0,0,False,False,...,False,False,False,True,False,False,False,False,False,True

In [56]:
from sklearn.linear_model import LogisticRegression
import numpy as np

In [84]:
lr = LogisticRegression()
X = np.column_stack((np.ones(len(df_dummy)), df_dummy.drop(columns=['y']))) # create the confusion matrix, and drop the response variable

In [86]:
X

array([[1.0, 58, 2143, ..., False, False, True],
       [1.0, 44, 29, ..., False, False, True],
       [1.0, 33, 2, ..., False, False, True],
       ...,
       [1.0, 72, 5715, ..., False, True, False],
       [1.0, 57, 668, ..., False, False, True],
       [1.0, 37, 2971, ..., True, False, False]], dtype=object)

In [88]:
lr.fit(X,df_dummy['y'])

C:\Users\PC04\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [90]:
from sklearn.metrics import confusion_matrix

confusion_matrix(df_dummy['y'],lr.predict(X))

array([[39200,   722],
       [ 4097,  1192]], dtype=int64)

In [92]:
df_dummy.shape

(45211, 43)

In [94]:
# accuracy rate and err_rate
acc_rate=(39200+1192)/45211
err_rate= (722+4097)/45211

In [96]:
acc_rate
# the model performance is 89% but this is the train data. 
# Most of the data is y=0 (39123+709) and the % of getting correct class is 95%
# for class y=1, the % only 1086/5289=20%

0.8934108955785096

In [98]:
err_rate

0.10658910442149035